// ============================================================
// Kroma — Sample Homemade Flower Vase & Floral Artifacts Data
// ============================================================

import type { Product, Category, HeroSlide } from '@/types';

export const SAMPLE_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Baskets & Arrangements',
    slug: 'baskets-arrangements',
    description: 'Charming wicker baskets and floral arrangements for tables and mantels',
    image_url: '/samples/2/pomelli_photoshoot-1.png',
    parent_id: null,
    sort_order: 1,
    created_at: '2024-01-01',
  },
  {
    id: 'cat-2',
    name: 'Wall Mounts',
    slug: 'wall-mounts',
    description: 'Bespoke wall-mounted floral plaques and pocket vases',
    image_url: '/samples/5/pomelli_photoshoot-1.png',
    parent_id: null,
    sort_order: 2,
    created_at: '2024-01-01',
  },
  {
    id: 'cat-3',
    name: 'Floral Wreaths',
    slug: 'floral-wreaths',
    description: 'Homemade decorative door and wall wreaths',
    image_url: '/samples/1/pomelli_photoshoot-1.png',
    parent_id: null,
    sort_order: 3,
    created_at: '2024-01-01',
  },
  {
    id: 'cat-4',
    name: 'Table Vases',
    slug: 'table-vases',
    description: 'Elegant homemade vase arrangements for table centerpieces',
    image_url: '/samples/10/pomelli_photoshoot-1.png',
    parent_id: null,
    sort_order: 4,
    created_at: '2024-01-01',
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Pomelli Harvest Wreath',
    slug: 'pomelli-harvest-wreath',
    description: 'A beautiful homemade harvest-style floral wreath featuring warm orange and peach blossoms, lush green leaves, and a rustic burlap ribbon bow. Meticulously handcrafted, this piece is perfect for door decor or bringing warmth to your entryways.',
    category_id: 'cat-3',
    price: 3200,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-WRTH-001',
    stock_quantity: 8,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['wreath', 'homemade', 'door decor', 'peach', 'orange'],
    created_at: '2024-06-01',
    updated_at: '2024-06-01',
    images: [
      { id: 'img-1-4', product_id: 'prod-1', image_url: '/samples/1/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Harvest Wreath styling' },
      { id: 'img-1-1', product_id: 'prod-1', image_url: '/samples/1/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Harvest Wreath front view' },
      { id: 'img-1-2', product_id: 'prod-1', image_url: '/samples/1/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Harvest Wreath detail' },
      { id: 'img-1-3', product_id: 'prod-1', image_url: '/samples/1/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Harvest Wreath side angle' },
    ],
    average_rating: 4.8,
    review_count: 15,
    total_orders: 43,
  },
  {
    id: 'prod-2',
    title: 'Pomelli Velvet Rose Bouquet',
    slug: 'pomelli-velvet-rose-bouquet',
    description: 'A gorgeous homemade centerpiece featuring deep crimson and pastel pink velvet roses, nested elegantly in a modern dark round box. Adds instant romance, color, and premium luxury to any table setting.',
    category_id: 'cat-1',
    price: 4800,
    sale_price: 4500,
    sale_start: '2024-01-01',
    sale_end: '2025-12-31',
    sku: 'PM-ARR-002',
    stock_quantity: 12,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['bouquet', 'velvet roses', 'hatbox', 'centerpiece', 'pink', 'red'],
    created_at: '2024-06-05',
    updated_at: '2024-06-05',
    images: [
      { id: 'img-2-4', product_id: 'prod-2', image_url: '/samples/2/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Velvet Rose Bouquet styling' },
      { id: 'img-2-1', product_id: 'prod-2', image_url: '/samples/2/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Velvet Rose Bouquet' },
      { id: 'img-2-2', product_id: 'prod-2', image_url: '/samples/2/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Velvet Rose Bouquet detail' },
      { id: 'img-2-3', product_id: 'prod-2', image_url: '/samples/2/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Velvet Rose Bouquet alternate angle' },
    ],
    average_rating: 4.9,
    review_count: 22,
    total_orders: 58,
  },
  {
    id: 'prod-3',
    title: 'Pomelli Orchid Wicker Basket',
    slug: 'pomelli-orchid-wicker-basket',
    description: 'Exquisite white orchids and soft yellow calla lilies arranged in a hand-woven wicker basket. This homemade floral artifact brings fresh, natural serenity and refined taste to your living space.',
    category_id: 'cat-1',
    price: 3600,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-BSKT-003',
    stock_quantity: 6,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['wicker', 'basket', 'orchids', 'white', 'floral arrangement'],
    created_at: '2024-06-10',
    updated_at: '2024-06-10',
    images: [
      { id: 'img-3-4', product_id: 'prod-3', image_url: '/samples/3/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Orchid Wicker Basket styling' },
      { id: 'img-3-1', product_id: 'prod-3', image_url: '/samples/3/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Orchid Wicker Basket' },
      { id: 'img-3-2', product_id: 'prod-3', image_url: '/samples/3/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Orchid Wicker Basket detail' },
      { id: 'img-3-3', product_id: 'prod-3', image_url: '/samples/3/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Orchid Wicker Basket side view' },
    ],
    average_rating: 4.7,
    review_count: 14,
    total_orders: 39,
  },
  {
    id: 'prod-4',
    title: 'Pomelli Sunshine Floral Basket',
    slug: 'pomelli-sunshine-floral-basket',
    description: 'A vibrant homemade floral arrangement in a woven basket, bursting with saffron yellow orchids, orange wild blossoms, and rich green foliage. Designed to radiate positive energy and brightness.',
    category_id: 'cat-1',
    price: 3800,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-BSKT-004',
    stock_quantity: 15,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['yellow', 'sunshine', 'orchids', 'basket', 'vibrant'],
    created_at: '2024-06-12',
    updated_at: '2024-06-12',
    images: [
      { id: 'img-4-4', product_id: 'prod-4', image_url: '/samples/4/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Sunshine Floral Basket styling' },
      { id: 'img-4-1', product_id: 'prod-4', image_url: '/samples/4/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Sunshine Floral Basket' },
      { id: 'img-4-2', product_id: 'prod-4', image_url: '/samples/4/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Sunshine Floral Basket detail' },
      { id: 'img-4-3', product_id: 'prod-4', image_url: '/samples/4/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Sunshine Floral Basket alternate angle' },
    ],
    average_rating: 4.6,
    review_count: 19,
    total_orders: 84,
  },
  {
    id: 'prod-5',
    title: 'Pomelli Hydrangea Wall Pocket',
    slug: 'pomelli-hydrangea-wall-pocket',
    description: 'A unique homemade wall-mounted decoration featuring a ribbed white ceramic half-pocket vase on a polished wooden plaque, overflowing with lush lavender hydrangeas and soft pink roses.',
    category_id: 'cat-2',
    price: 5500,
    sale_price: 4900,
    sale_start: '2024-01-01',
    sale_end: '2025-12-31',
    sku: 'PM-WALL-005',
    stock_quantity: 5,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['wall pocket', 'wood plaque', 'ceramic', 'hydrangea', 'roses', 'purple'],
    created_at: '2024-06-08',
    updated_at: '2024-06-08',
    images: [
      { id: 'img-5-4', product_id: 'prod-5', image_url: '/samples/5/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Hydrangea Wall Pocket styling' },
      { id: 'img-5-1', product_id: 'prod-5', image_url: '/samples/5/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Hydrangea Wall Pocket' },
      { id: 'img-5-2', product_id: 'prod-5', image_url: '/samples/5/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Hydrangea Wall Pocket detail' },
      { id: 'img-5-3', product_id: 'prod-5', image_url: '/samples/5/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Hydrangea Wall Pocket alternate angle' },
    ],
    average_rating: 4.8,
    review_count: 11,
    total_orders: 31,
  },
  {
    id: 'prod-6',
    title: 'Pomelli Blush Meadow Frame',
    slug: 'pomelli-blush-meadow-frame',
    description: 'An exquisite homemade floral wall frame. A sleek dark charcoal square frame cradles a rich collection of pink roses, violet delphiniums, and white hydrangeas, creating a three-dimensional garden painting.',
    category_id: 'cat-2',
    price: 6800,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-WALL-006',
    stock_quantity: 4,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['wall frame', 'floral painting', 'delphinium', 'hydrangea', 'roses', 'pink'],
    created_at: '2024-06-15',
    updated_at: '2024-06-15',
    images: [
      { id: 'img-6-4', product_id: 'prod-6', image_url: '/samples/6/pomelli_creative_image_9_16_0615 (1).png', sort_order: 1, alt_text: 'Pomelli Blush Meadow Frame styling' },
      { id: 'img-6-1', product_id: 'prod-6', image_url: '/samples/6/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Blush Meadow Frame' },
      { id: 'img-6-2', product_id: 'prod-6', image_url: '/samples/6/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Blush Meadow Frame close-up' },
      { id: 'img-6-3', product_id: 'prod-6', image_url: '/samples/6/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Blush Meadow Frame angle view' },
    ],
    average_rating: 5.0,
    review_count: 9,
    total_orders: 18,
  },
  {
    id: 'prod-7',
    title: 'Pomelli Golden Lavender Plaque',
    slug: 'pomelli-golden-lavender-plaque',
    description: 'A wall-mounted golden textured vase set against a dark gray slate panel, containing a whimsical arrangement of purple daisies, pink orchids, and green sprigs. Homemade with attention to high contrast and rich textures.',
    category_id: 'cat-2',
    price: 5900,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-WALL-007',
    stock_quantity: 6,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['wall plaque', 'gold vase', 'slate', 'lavender', 'purple'],
    created_at: '2024-06-14',
    updated_at: '2024-06-14',
    images: [
      { id: 'img-7-4', product_id: 'prod-7', image_url: '/samples/7/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Golden Lavender Plaque styling' },
      { id: 'img-7-1', product_id: 'prod-7', image_url: '/samples/7/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Golden Lavender Plaque' },
      { id: 'img-7-2', product_id: 'prod-7', image_url: '/samples/7/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Golden Lavender Plaque close-up' },
      { id: 'img-7-3', product_id: 'prod-7', image_url: '/samples/7/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Golden Lavender Plaque detail' },
    ],
    average_rating: 4.7,
    review_count: 8,
    total_orders: 26,
  },
  {
    id: 'prod-8',
    title: 'Pomelli Spring Rose Meadow',
    slug: 'pomelli-spring-rose-meadow',
    description: 'A premium homemade flower basket rich in light pink roses, blushing dahlias, and delicate purple wildflowers. Hand-arranged to capture the freshness of a sunlit spring morning.',
    category_id: 'cat-1',
    price: 4200,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-BSKT-008',
    stock_quantity: 10,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['basket', 'spring', 'roses', 'pink', 'dahlias'],
    created_at: '2024-06-11',
    updated_at: '2024-06-11',
    images: [
      { id: 'img-8-4', product_id: 'prod-8', image_url: '/samples/8/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Spring Rose Meadow styling' },
      { id: 'img-8-1', product_id: 'prod-8', image_url: '/samples/8/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Spring Rose Meadow' },
      { id: 'img-8-2', product_id: 'prod-8', image_url: '/samples/8/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Spring Rose Meadow close-up' },
      { id: 'img-8-3', product_id: 'prod-8', image_url: '/samples/8/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Spring Rose Meadow side view' },
    ],
    average_rating: 4.8,
    review_count: 16,
    total_orders: 51,
  },
  {
    id: 'prod-9',
    title: 'Pomelli Ribboned Garden Basket',
    slug: 'pomelli-ribboned-garden-basket',
    description: 'An adorable homemade basket design using braided seagrass, dressed with delicate white lace trim and a bow. Contains a colorful selection of scarlet ranunculus, orange roses, and purple anemones.',
    category_id: 'cat-1',
    price: 4500,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-BSKT-009',
    stock_quantity: 7,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['basket', 'ribbon', 'lace', 'ranunculus', 'roses'],
    created_at: '2024-06-07',
    updated_at: '2024-06-07',
    images: [
      { id: 'img-9-4', product_id: 'prod-9', image_url: '/samples/9/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Ribboned Garden Basket styling' },
      { id: 'img-9-1', product_id: 'prod-9', image_url: '/samples/9/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Ribboned Garden Basket' },
      { id: 'img-9-2', product_id: 'prod-9', image_url: '/samples/9/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Ribboned Garden Basket detail' },
      { id: 'img-9-3', product_id: 'prod-9', image_url: '/samples/9/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Ribboned Garden Basket side view' },
    ],
    average_rating: 4.9,
    review_count: 20,
    total_orders: 68,
  },
  {
    id: 'prod-10',
    title: 'Pomelli Royal Azure Ribbed Bowl',
    slug: 'pomelli-royal-azure-ribbed-bowl',
    description: 'A stunning cobalt blue ribbed ceramic bowl vase with a delicate silver ribbon, showcasing premium handmade silk roses in peach, coral, and white. A table centerpiece that whispers sophisticated luxury.',
    category_id: 'cat-4',
    price: 7500,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-VASE-010',
    stock_quantity: 4,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['table vase', 'blue ceramic', 'roses', 'centerpiece', 'luxury'],
    created_at: '2024-06-16',
    updated_at: '2024-06-16',
    images: [
      { id: 'img-10-4', product_id: 'prod-10', image_url: '/samples/10/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Royal Azure Ribbed Bowl styling' },
      { id: 'img-10-1', product_id: 'prod-10', image_url: '/samples/10/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Royal Azure Ribbed Bowl' },
      { id: 'img-10-2', product_id: 'prod-10', image_url: '/samples/10/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Royal Azure Ribbed Bowl detail' },
      { id: 'img-10-3', product_id: 'prod-10', image_url: '/samples/10/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Royal Azure Ribbed Bowl alternate view' },
    ],
    average_rating: 5.0,
    review_count: 12,
    total_orders: 29,
  },
  {
    id: 'prod-11',
    title: 'Pomelli Summer Sunflower Basket',
    slug: 'pomelli-summer-sunflower-basket',
    description: 'Bright and joyful, this homemade wicker basket features vibrant sunflowers accented by red and orange wildflowers. Bring the warmth, sunshine, and happiness of a summer field into your home.',
    category_id: 'cat-1',
    price: 3400,
    sale_price: null,
    sale_start: null,
    sale_end: null,
    sku: 'PM-BSKT-011',
    stock_quantity: 11,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    meta_title: null,
    meta_description: null,
    og_image_url: null,
    tags: ['sunflower', 'wicker', 'basket', 'yellow', 'summer'],
    created_at: '2024-06-13',
    updated_at: '2024-06-13',
    images: [
      { id: 'img-11-4', product_id: 'prod-11', image_url: '/samples/11/pomelli_creative_image_9_16_0615.png', sort_order: 1, alt_text: 'Pomelli Summer Sunflower Basket styling' },
      { id: 'img-11-1', product_id: 'prod-11', image_url: '/samples/11/pomelli_photoshoot-1.png', sort_order: 2, alt_text: 'Pomelli Summer Sunflower Basket' },
      { id: 'img-11-2', product_id: 'prod-11', image_url: '/samples/11/pomelli_photoshoot-2.png', sort_order: 3, alt_text: 'Pomelli Summer Sunflower Basket detail' },
      { id: 'img-11-3', product_id: 'prod-11', image_url: '/samples/11/pomelli_photoshoot-3.png', sort_order: 4, alt_text: 'Pomelli Summer Sunflower Basket side angle' },
    ],
    average_rating: 4.8,
    review_count: 18,
    total_orders: 47,
  },
];

export const SAMPLE_HERO_SLIDES: HeroSlide[] = [
  {
    id: 'hero-1',
    image_url: '/samples/hero-1.png',
    heading: 'Homemade Floral Artistry',
    subheading: 'Custom flower vase arrangements designed by Pomelli, handmade with love to warm your home.',
    cta_text: 'Explore Collection',
    cta_link: '/products',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'hero-2',
    image_url: '/samples/hero-2.png',
    heading: 'Baskets & Arrangements',
    subheading: 'Charming wicker baskets, wreaths, and table centerpieces for beautiful settings.',
    cta_text: 'Shop Baskets',
    cta_link: '/products?category=baskets-arrangements',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'hero-3',
    image_url: '/samples/hero-3.png',
    heading: 'Bespoke Wall Mounts',
    subheading: 'Three-dimensional wall plaques and pocket vases that redefine modern wall decor.',
    cta_text: 'View Wall Mounts',
    cta_link: '/products?category=wall-mounts',
    sort_order: 3,
    is_active: true,
  },
];

export const SAMPLE_TESTIMONIALS = [
  {
    id: 'test-1',
    name: 'Priya Sharma',
    text: 'The Pomelli Velvet Rose Bouquet is absolutely stunning. It\'s become the centerpiece of my dining table. The homemade touch makes it truly unique.',
    rating: 5,
    avatar: '/samples/avatar-1.png',
  },
  {
    id: 'test-2',
    name: 'Arjun Mehta',
    text: 'Ordered the Blush Meadow Wall Frame as a gift for my mother. It arrived beautifully packed, and the floral quality was unbelievable. Recommended!',
    rating: 5,
    avatar: '/samples/avatar-2.png',
  },
  {
    id: 'test-3',
    name: 'Ananya Rao',
    text: 'Pomelli\'s attention to detail is extraordinary. The Sunflower Wicker Basket catches light in ways that genuinely make my kitchen feel bright and happy.',
    rating: 5,
    avatar: '/samples/avatar-3.png',
  },
];

export const TRUST_BADGES = [
  { icon: '🎨', text: 'Homemade Artifacts' },
  { icon: '📦', text: 'Free Shipping over ₹3000' },
  { icon: '🔄', text: '30-Day Returns' },
  { icon: '🛡️', text: 'Secure Packaging' },
  { icon: '✨', text: 'Handcrafted Quality' },
  { icon: '🌿', text: 'Eco-Friendly Designs' },
];
